funboxtest_homepage:
    path:     /funbox/
    defaults: { _controller: funboxtestBundle:Default:index }
funboxtest_adminPage:
    path:     /funbox/admin/
    defaults: { _controller: funboxtestBundle:Default:showAdmin }
funboxtest_addAdminPage:
    path:     /funbox/admin/add/
    defaults: { _controller: funboxtestBundle:Default:addAdmin }
funboxtest_editAdminPage:
    path:     /funbox/admin/edit/{id}
    defaults: { _controller: funboxtestBundle:Default:editAdmin }
funboxtest_deleteAdminPage:
    path:     /funbox/admin/delete/{id}
    defaults: { _controller: funboxtestBundle:Default:deleteAdmin }
funboxtest_miscAdminPage:
    path:     /funbox/admin/misc/
    defaults: { _controller: funboxtestBundle:Default:miscAdmin }
funboxtest_searchResultsPage:
    path:     /funbox/search/{q}
    defaults: { _controller: funboxtestBundle:Default:searchResults }