funboxtest_hellopage:
    path:     /hello/{name}
    defaults: { _controller: funboxtestBundle:Default:hello }
funboxtest_homepage:
    path:     /funbox/
    defaults: { _controller: funboxtestBundle:Default:index }
funboxtest_add:
    path:     /funbox/create/
    defaults: { _controller: funboxtestBundle:Default:create }
funboxtest_showAll:
    path:     /funbox/show/
    defaults: { _controller: funboxtestBundle:Default:showAll }
funboxtest_adminPage:
    path:     /funbox/admin/
    defaults: { _controller: funboxtestBundle:Default:showAdmin }
funboxtest_editAdminPage:
    path:     /funbox/admin/edit/
    defaults: { _controller: funboxtestBundle:Default:editAdmin }